---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
      - develop
    tags:
      - v*
  pull_request:
    branches:
      - main
      - develop

jobs:
  integration:
    name: Integration Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install libvirt
        run: >-
          sudo apt-get update &&
          sudo apt-get install --yes
          libvirt-clients
          libvirt-daemon-system
          qemu-kvm
          xsltproc

      - name: Setup Tofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: latest

      - name: Permissions workaround
        run: |
          sudo sed -i -r 's/^#?[[:space:]]*security_driver[[:space:]]*=[^=]+/security_driver = "none"/' /etc/libvirt/qemu.conf
          sudo sed -i -r 's/^#?[[:space:]]*auth_unix_ro[[:space:]]*=[^=]+/auth_unix_ro = "polkit"/' /etc/libvirt/libvirtd.conf
          sudo sed -i -r 's/^#?[[:space:]]*auth_unix_rw[[:space:]]*=[^=]+/auth_unix_rw = "polkit"/' /etc/libvirt/libvirtd.conf
          sudo install -o root -g root -m 0644 -D .github/workflow-templates/socket-perms.conf /etc/systemd/system/libvirtd.socket.d/socket-perms.conf
          sudo chmod 755 /var/lib/libvirt/images
          sed "s/{{USER}}/${USER}/g" < .github/workflow-templates/80-libvirt-manage.rules.tpl | sudo tee /etc/polkit-1/rules.d/80-libvirt-manage.rules > /dev/null
          sudo systemctl daemon-reload
          sudo systemctl restart libvirtd.socket libvirtd.service
          stat /var/run/libvirt/libvirt-sock

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Run tofu
        run: |
          tofu init &&
          tofu apply -auto-approve
